## Read the data

This code will give you the data you will use for this PC:

In [14]:
# read web table into pandas DF
import pandas as pd

co2Link='https://docs.google.com/spreadsheets/d/e/2PACX-1vRXjfxeKHQBBCh_oHP-D6RIHEX4eduLjydHb6ZGsU4jo0IK0KKQSoYX_X1FGssC_9hnqCgjKN0K4AVf/pub?gid=775098192&single=true&output=csv'
carbon=pd.read_csv(co2Link)

In [15]:
# here it is:
carbon

,name,metric tonnes of CO2,date_of_information,ranking,region
0,China,1.219600e+10,2023,1,East and Southeast Asia
1,United States,4.795000e+09,2023,2,North America
2,India,2.821000e+09,2023,3,South Asia
3,Russia,1.844000e+09,2023,4,Central Asia
4,Japan,9.602300e+08,2023,5,East and Southeast Asia
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,212,South America
212,Montserrat,2.400000e+01,2023,213,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,214,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,215,Africa
215,Niue,9.000000e+00,2023,216,Australia and Oceania

As you see, some columns have space, which should be deleted:

In [27]:
# also
carbon.columns

Index(['name', 'metric_tonnes_of_CO2', 'date_of_information', 'ranking',
       'region'],
      dtype='object')

In [17]:
# Like this
carbon.rename(columns={'metric tonnes of CO2':'metric_tonnes_of_CO2'},inplace=True)

# see
carbon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  216 non-null    object
 1   metric_tonnes_of_CO2  216 non-null    float64
 2   date_of_information   216 non-null    int64
 3   ranking               216 non-null    int64
 4   region                216 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 8.6+ KB

You always make a copy:

In [28]:
carbon_copy=carbon.copy()

In [29]:
byeColumns=['ranking'] #1- eliminando columna ranking
carbon_copy.drop(columns=byeColumns,inplace=True)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region
0,China,1.219600e+10,2023,East and Southeast Asia
1,United States,4.795000e+09,2023,North America
2,India,2.821000e+09,2023,South Asia
3,Russia,1.844000e+09,2023,Central Asia
4,Japan,9.602300e+08,2023,East and Southeast Asia
...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa
215,Niue,9.000000e+00,2023,Australia and Oceania

In [31]:
carbon_copy[carbon_copy.metric_tonnes_of_CO2==min(carbon_copy.metric_tonnes_of_CO2)]['name']
#2- usando min para hallar el minimo emisor de co2 en la columna que indica emisiones y ['name'] para que de el pais en sÃ­

215    Niue
Name: name, dtype: object

In [36]:
conjunto_region=set(carbon_copy.region)
conjunto_region
#creacion de un conjunto a partir de la columna region para observar cuales son las regiones sin que se repitan (en la taba no salen todas)

{'Africa',
 'Antarctica',
 'Australia and Oceania',
 'Central America and the Caribbean',
 'Central Asia',
 'East and Southeast Asia',
 'Europe',
 'Middle East',
 'North America',
 'South America',
 'South Asia'}

In [37]:
carbon_copy[carbon_copy.region=='Africa'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]
#toma todos los paises que tengan region africa, los ordena de forma ascendente en base al CO2 y retorna la primera posicion osea el de menor emision
#la logica se sigue para las siguientes lineas para cada region

'Saint Helena, Ascension, and Tristan da Cunha'

In [38]:
carbon_copy[carbon_copy.region=='Antarctica'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Antarctica'

In [39]:
carbon_copy[carbon_copy.region=='Australia and Oceania'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Niue'

In [40]:
carbon_copy[carbon_copy.region=='Central America and the Caribbean'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Montserrat'

In [41]:
carbon_copy[carbon_copy.region=='Central Asia'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Armenia'

In [42]:
carbon_copy[carbon_copy.region=='East and Southeast Asia'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Timor-Leste'

In [43]:
carbon_copy[carbon_copy.region=='Europe'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Faroe Islands'

In [44]:
carbon_copy[carbon_copy.region=='Middle East'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'West Bank'

In [45]:
carbon_copy[carbon_copy.region=='North America'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Saint Pierre and Miquelon'

In [46]:
carbon_copy[carbon_copy.region=='South America'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Falkland Islands (Islas Malvinas)'

In [47]:
carbon_copy[carbon_copy.region=='South Asia'].sort_values(by=['metric_tonnes_of_CO2'],ascending=True).iloc[0,0]

'Bhutan'

In [89]:
def sqrt_CO2(numero):
  numsqrt=numero**(1/2)
  return numsqrt
  #definir la funcion que saca raiz cuadrada

In [90]:
#4-
raizCO2=carbon_copy.loc[:,'metric_tonnes_of_CO2'].apply(sqrt_CO2)
#"crear" la nueva columna aplicando la funcion raiz a la columna de emisiones
carbon_copy=carbon_copy.assign(sqrtCO2=raizCO2)
#incorporar la nueva columna
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,raiz_CO2,sqrtCO2
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538,110435.501538
1,United States,4.795000e+09,2023,North America,69245.938509,69245.938509
2,India,2.821000e+09,2023,South Asia,53113.086900,53113.086900
3,Russia,1.844000e+09,2023,Central Asia,42941.821107,42941.821107
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156,30987.578156
...,...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000,6.000000
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979,4.898979
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983,3.872983
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102,3.464102
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000,3.000000

In [68]:
#def sumatotal(numero,suma=0):
  #suma=suma+numero
  #return suma

In [75]:
#lista_co2=list(carbon_copy.metric_tonnes_of_CO2)

In [80]:
#total_CO2=lista_co2[0]
#for i in range(1,len(lista_co2)):
  #total_CO2=sumatotal(lista_co2[i],total_CO2)

#total_CO2
#TODO ESE MÃ‰TODO ARRIBA EN VERDE ES OTRA FORMA DE HACERLO QUE DESARROLLE APARTE DE LA MOSTRADA A LA CONTINUACIÃ“N

In [91]:
total_CO2 = carbon_copy['metric_tonnes_of_CO2'].sum()
numero_paises=len(carbon_copy.metric_tonnes_of_CO2)
promedio_CO2=total_CO2/numero_paises
promedio_CO2
#Se halla el promedio primero

np.float64(171564562.3412037)

In [92]:
def restaCO2(numero,promedio_CO2):
  resta=numero-promedio_CO2
  return resta
#Funcion para calcular la resta entre el co2 original y el promedio

In [97]:
#5
resta=carbon_copy.loc[:,'metric_tonnes_of_CO2'].apply(restaCO2,args=(promedio_CO2,))
#"crear" la nueva columna aplicando la funcion raiz a la columna de emisiones
carbon_copy=carbon_copy.assign(Minus_average=resta)
#incorporar la nueva columna
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region,raiz_CO2,sqrtCO2,Minus_average
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538,110435.501538,1.202444e+10
1,United States,4.795000e+09,2023,North America,69245.938509,69245.938509,4.623435e+09
2,India,2.821000e+09,2023,South Asia,53113.086900,53113.086900,2.649435e+09
3,Russia,1.844000e+09,2023,Central Asia,42941.821107,42941.821107,1.672435e+09
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156,30987.578156,7.886654e+08
...,...,...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000,6.000000,-1.715645e+08
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979,4.898979,-1.715645e+08
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983,3.872983,-1.715645e+08
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102,3.464102,-1.715646e+08
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000,3.000000,-1.715646e+08

## Questions

Complete the tasks requested using **carbon_copy**:

1. Keep all the columns but _Ranking_:
    * Tip: use [drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html), [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html), and [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) for the same purpose (three ways to accomplish the task).

2. Find the country with the minimum CO2 emission in the world.

3. Find the country with the minimum CO2 emission per Region.

4. Create a new column by keeping the square root of the the original CO2  column.

5. Compute the average of CO2. Then, create a new column. This new column is
the original CO2 minus the average computed.

You have changed **carbon_copy**, now save it as a file like this:

In [ ]:
# carbon_copy.to_csv("carbon_copy.csv",index=False)